LABEL version="1.0" \
  maintainer="IG Stark Team <DL-Stark@insightglobal.net>"

ARG DOCKER_REPOSITORY_USERNAME
ARG DOCKER_REPOSITORY_PASSWORD
ARG TRIVY_USERNAME
ARG TRIVY_PASSWORD
ARG Token
ENV CONFIGURATION_SERVICE_URL="http://configuration-service:8888"
ENV CONFIGURATION_SERVICE_PROFILE="devn3"
ENV COMTRAK_CONFIG_DIR="/etc/comtrak"
ENV DEPLOYMENT_BASE_DIR="/data"
ENV STAGE_DIR="/tmp"
# TODO: Move logging to /var/log/comtrak (Set in configuration service's comtrak.yml "'internal.'log directory'")
ENV COMTRAK_LOG_DIR="/data/log"

ENV ARTIFACTORY_DOWNLOAD_URL="https://cloudigart.jfrog.io/artifactory/libs-release-local/com/insightglobal/comtrak"

ENV COMTRAK_CONFIGURATION_SERVICE_CLIENT_APP="comtrak_configuration_service_client"
ENV COMTRAK_CONFIGURATION_SERVICE_CLIENT_VERSION="1.0.24-20220403121337"
ENV COMTRAK_CONFIGURATION_SERVICE_CLIENT_PACKAGE="${COMTRAK_CONFIGURATION_SERVICE_CLIENT_APP}-${COMTRAK_CONFIGURATION_SERVICE_CLIENT_VERSION}"
ENV COMTRAK_CONFIGURATION_SERVICE_CLIENT_ARCHIVE="${COMTRAK_CONFIGURATION_SERVICE_CLIENT_PACKAGE}-bin.zip"
ENV COMTRAK_CONFIGURATION_SERVICE_CLIENT_DOWNLOAD_URL="${ARTIFACTORY_DOWNLOAD_URL}/${COMTRAK_CONFIGURATION_SERVICE_CLIENT_VERSION}/${COMTRAK_CONFIGURATION_SERVICE_CLIENT_ARCHIVE}"
